cache:
  paths:
    - ~/.cache/pip/


image: "python:3.9"

services:
  - mongo:4.4.12

before_script:
    - python3 -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install pylint
    - pip install mongomock
    - pip install -r requirements.txt
    - pip install .

stages:
    - Static Analysis
    - Test

pylint:
  stage: Static Analysis
  tags:
    - docker
  script:
    - pylint -d C0301 src/*/*.py

tests:
  stage: Test
  tags:
    - docker
  script:
    - python3 -m unittest
#  artifacts:
#    when: always
#    reports:
#      junit: report.xml
